---
- hosts: all
  gather_facts: yes
  become: true

  pre_tasks:

   - name: Install Python
     command: sudo yum install python -y
     when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or
           (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

   - name: Install python
     apt:
       name: python
       state: present
     when:
       - ansible_distribution == "Debian"
       - ansible_distribution == "Ubuntu"

   - name: Install Python-Pip
     command: sudo apt install python-pip -y
     when:
       - ansible_distribution == "Debian"
       - ansible_distribution == "Ubuntu"


   - name: Create Folder
     file:
       path: /tmp/ssm
       state: directory
       mode: 0755

   - name: Accessing Folder
     shell: cd /tmp/ssm

  tasks:
   - include: /etc/ansible/ssm.yml
